<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-macos15.0</TargetFramework>
    <SupportedOSPlatformVersion>14.0</SupportedOSPlatformVersion>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <ApplicationId>org.greenshot.mac</ApplicationId>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <ValidateXcodeVersion>false</ValidateXcodeVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Greenshot.Platform.Mac\Greenshot.Platform.Mac.csproj" />
    <PackageReference Include="Avalonia" Version="11.3.9" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
  </ItemGroup>
</Project>
